# 错误处理机制-异常

程序的错误处理，在我们编写代码时很容易被忽略，其实它还是比较重要的。

## 为什么程序需要一个异常机制

**没有异常的时候，程序出错会怎么样?** **一旦出错，系统会整个崩溃，会导致以下两个子问题**


  1.出错整个程序就瘫痪了

  2.没法得知错误具体信息
  
  这点是最为重要的，还记得我们平时怎么排查错误的吗，就是读取错误信息找到错误代码

### 处理异常情况，恢复运行

可以做到尽**可能在出错的时候去处理这个错误**，告诉**系统可以继续运行，并且把错误信息尽可能告知我们**

```js
try{
  throw new Error('出错')
}catch(e){
  console.log('捕获到了异常', e)
} 
console.log('系统继续运行') //这里会被运行
```

异常除了让程序不至于整体崩溃，还回答了三个问题：

* 什么出了错 错误堆栈

* 在哪出的错 错误堆栈

* 为什么出错 message

### js现有错误类型：
```js
Error 
// 顶级父类 通常作为自定义异常父类使用

EvalError 
// 没有把eval当成函数调用，就会出错 eg: new eval eval由于性能非常之低，使用需要十分谨慎

RangeError
// 数值超出范围 let items = new Array(Number.MAX_VALUE)

ReferenceError 常见
// 访问不存在的变量 let obj = x

SyntaxError 常见
// 语法上不正确

TypeError 常见
//  被操作数的类型不满足此操作 eg: let obj = new 10

URIError
// encodeURI()或decodeURI() URL不符合规范时报错
```    

## 捕获异常

捕获错误的目的在于避免浏览器以默认方式处理它们


try-catch-finally
```js
  try{
    // 可能发生异常的代码
    someFunction()
  } catch(error){
    if(error instanceof TypeError){
      //处理类型错误
    } else if (error instanceof ReferenceError) {
      //处理引用错误
    } else {
      //处理其他错误
    }
  } finally {
    // 始终要做的 比如关闭数据库连接
  }
```

## 抛出异常

抛出错误的目的在于提供错误发生具体原因的消息，在程序不能处理现场时，抛出异常通知程序


抛出错误: throw obj (obj istanceof Error) 通常采用Error子类
```js
  function MyError (message) {
    this.message = message
  }

  MyError.prototype = new Error()

  throw new MyError('我定义的错误')
```



